# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac97ac51c45084ea32048cfeb037278e2fa7d5baa0200c043586ad934bfd255717faa48ad4a8d184d1ce39f70d57a480e4fcf3d7411a9be1c4c5cfb1ce94b980

test:
  secret_key_base: c98b9c280ff997baea9a90ed0b4c6cf6a834678cd1f714ecc8e5e6baf90b0c81277b38b7c0943194a4f97a0818224026e4b0db9b90918d76018e127b520073bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
